// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBTZVamoqpQpoylia5Q3dvuL2ruEHg94U',
    appId: '1:1027779138763:web:6c1367d933a712a73cf74e',
    messagingSenderId: '1027779138763',
    projectId: 'torneios-app-800e0',
    authDomain: 'torneios-app-800e0.firebaseapp.com',
    storageBucket: 'torneios-app-800e0.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBBo8eXDAq3942zhMSnoWdmfigUvHtU8hM',
    appId: '1:1027779138763:android:f8528a96df9a71903cf74e',
    messagingSenderId: '1027779138763',
    projectId: 'torneios-app-800e0',
    storageBucket: 'torneios-app-800e0.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVuRTnxUTlodP53P0p9uqBoWbGJvPke3c',
    appId: '1:1027779138763:ios:f5d8d03506b3e70e3cf74e',
    messagingSenderId: '1027779138763',
    projectId: 'torneios-app-800e0',
    storageBucket: 'torneios-app-800e0.firebasestorage.app',
    iosBundleId: 'com.example.torneiosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVuRTnxUTlodP53P0p9uqBoWbGJvPke3c',
    appId: '1:1027779138763:ios:f5d8d03506b3e70e3cf74e',
    messagingSenderId: '1027779138763',
    projectId: 'torneios-app-800e0',
    storageBucket: 'torneios-app-800e0.firebasestorage.app',
    iosBundleId: 'com.example.torneiosApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBTZVamoqpQpoylia5Q3dvuL2ruEHg94U',
    appId: '1:1027779138763:web:fa5eac6d5aa2421d3cf74e',
    messagingSenderId: '1027779138763',
    projectId: 'torneios-app-800e0',
    authDomain: 'torneios-app-800e0.firebaseapp.com',
    storageBucket: 'torneios-app-800e0.firebasestorage.app',
  );
}
